language: python
python: '2.7'
install: pip install requests requests_oauthlib httpretty
script: python -m unittest discover -v
deploy:
  provider: pypi
  on:
    tags: true
  user: abiquo
  password:
    secure: LuupLqFXi3NeIVNUaGk8h+usy//lP+tCP7zpzwdkZznhppW3B1ae39Qr74JUGrw78e1UWX23tDteheMJBncSiNpWFexo25+XgY8oEyxaMkcIoVSnCyh8FcyC/u09pUZFtwpjvc9rkmrkPMEodfKXH77ewD0TFC7+AC0Z9ZlJKrI=
